def pipeline_output(wildcards):
    """
    Custom function that returns a list of output files generated by the pipeline based on the config.
    Note that filtered.txt depends on the value of the config["filter"] parameter in the config.yaml file.
    """
    outputs = []
    outputs.extend(["test.txt"])
    if config["filter"]:
        outputs.extend(["filtered.txt"])
    return outputs